name = "crm-sda"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "crm-sda"
database_id = "b0fd2569-05f1-4396-b70d-c9306c0c1863"
migrations_dir = "migrations"
